name: "📚 Documentation Improvement"
description: Suggest improvements or report errors in the Cooper documentation.
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Cooper is a documentation-first boilerplate. Helping us improve the docs is highly appreciated!
  - type: input
    id: page
    attributes:
      label: Documentation Page
      description: Which page(s) should be improved?
      placeholder: e.g., /docs/ui/buttons
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What is wrong or missing?
      description: Please describe the issue with the current documentation.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you like to see the documentation improved?
    validations:
      required: true
